Split package into tools and lib subpackages
conda-forge/libgcrypt-feedstock pull request #28
Opened 2024-11-22 13:12 UTC by pavelzw

Checklist
* [x] Used a [personal fork of the feedstock to propose changes](https://conda-forge.org/docs/maintainer/updating_pkgs.html#forking-and-pull-requests)
* [x] Bumped the build number (if the version is unchanged)
* [x] Reset the build number to `0` (if the version changed)
* [ ] [Re-rendered]( https://conda-forge.org/docs/maintainer/updating_pkgs.html#rerendering-feedstocks ) with the latest `conda-smithy` (Use the phrase <code>@<space/>conda-forge-admin, please rerender</code> in a comment in this PR for automated rerendering)
* [x] Ensured the license file is being packaged.

2024-11-22 13:13 UTC, conda-forge-admin commented
Hi! This is the friendly automated conda-forge-linting service.

I wanted to let you know that I linted all conda-recipes in your PR (```recipe/meta.yaml```) and found some lint.

Here's what I've got...


For **recipe/meta.yaml**:

 * ❌ The `requirements/` sections should be defined in the following order: build, host, run; instead saw: host, build.


<sub>This message was generated by GitHub Actions workflow run [https://github.com/conda-forge/conda-forge-webservices/actions/runs/11973258322](https://github.com/conda-forge/conda-forge-webservices/actions/runs/11973258322). Examine the logs at this URL for more detail.</sub>

2024-11-22 13:14 UTC, xhochy requested changes

2024-11-22 13:14 UTC, xhochy commented on recipe/meta.yaml
> +        - test -f ${PREFIX}/lib/libgcrypt${SHLIB_EXT}.20.5.0  # [linux]    about:
```suggestion
        - test -f ${PREFIX}/lib/libgcrypt${SHLIB_EXT}.20.5.0  # [linux]
     about:
```

2024-11-22 13:14 UTC, xhochy commented on recipe/install-libgcrypt-devel.sh
> +rm $PREFIX/bin/libgcrypt-config
This is required for development
```suggestion
```

2024-11-22 13:19 UTC, conda-forge-admin commented
Hi! This is the friendly automated conda-forge-linting service.

I just wanted to let you know that I linted all conda-recipes in your PR (```recipe/meta.yaml```) and found it was in an excellent condition.

2024-11-23 12:13 UTC, pavelzw commented
@conda-forge/libgcrypt this is ready for review

2024-11-24 19:59 UTC, xhochy approved these changes

2024-11-25 08:21 UTC, merged

2024-11-25 08:22 UTC, xhochy commented
@pavelzw Please also update the build of `libsecret` to use the new output. Happy to review the PR over there.